server:
  port: ${server_port}

spring:
  application:
    name: Slick-Scheduler
  threads:
    virtual:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: headers
  task:
    scheduling:
      pool:
        size: 4

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${jasypt_encryptor_password}

logging:
  level:
    toy.slick.feign: debug

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  info:
    env:
      enabled: true

info:
  contact:
    email: wjdwo951219@gmail.com
  github: https://github.com/key824999/Slick-Scheduler

api:
  key:
    slick: ${api_key_slick}

telegram:
  bot:
    slick:
      apiToken: ENC(2FgpskdhK7pq5Wuax0WxeNiWV5t3jIUdkGAEnVSZ51DXFBGg4d9YhauQAYByel1yslTWbNa4iUv3s6yiLxYWNw==)
  chat:
    slick:
      id: ENC(UE0sacH3feg87lC3UdSB3VwwnHhgmyir)

password:
  executeSchedule: ENC(s2rZBXlFZBKBDlHc2Iw/gd/AYoaHzlDB)
