server:
  port: ${server_port}

spring:
  application:
    name: Slick-Scheduler
  threads:
    virtual:
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: headers
  task:
    scheduling:
      pool:
        size: 4
  data:
    mongodb:
      uri: mongodb+srv://${mongodb_username}:${mongodb_password}@slick-mongodb.4irbr6v.mongodb.net/?retryWrites=true&w=majority&appName=slick-mongodb
      database: slick-mongodb

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${jasypt_encryptor_password}

logging:
  level:
    toy.slick.feign: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  info:
    env:
      enabled: true

info:
  contact:
    email: wjdwo951219@gmail.com

telegram:
  bot:
    slick:
      apiToken: ENC(2FgpskdhK7pq5Wuax0WxeNiWV5t3jIUdkGAEnVSZ51DXFBGg4d9YhauQAYByel1yslTWbNa4iUv3s6yiLxYWNw==)
  chat:
    slick:
      id: ENC(UE0sacH3feg87lC3UdSB3VwwnHhgmyir)
